---
- name: Include OS-specific tasks
  include_tasks: "{{ lookup('first_found', files) }}"
  vars:
    - files:
        - '{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}.yml'

- name: Add the user '{{ mediaplayer_user_name }}'
  user:
    name: "{{ mediaplayer_user_name }}"
    group: audio
    comment: Mediaplayer
    home: "{{ mediaplayer_install_location }}/mediaplayer"
    system: yes

- name: "Download mediaplayer release {{ mediaplayer_version }}"
  get_url:
    url: "{{ mediaplayer_release_url }}"
    dest: "/usr/local/src/mediaplayer-{{ mediaplayer_version }}.zip"

- name: Unarchive mediaplayer release
  ansible.builtin.unarchive:
    src: "/usr/local/src/mediaplayer-{{ mediaplayer_version }}.zip"
    dest: "{{ mediaplayer_install_location }}"
    owner: "{{ mediaplayer_user_name }}"
    remote_src: yes
    keep_newer: yes
    # exclude:
    #   - "{{ mediaplayer_install_location }}/mediaplayer/RadioList.json.sample"
    #   - "{{ mediaplayer_install_location }}/mediaplayer/run.sh"
    #   - "{{ mediaplayer_install_location }}/mediaplayer/scripts"

- name: Removed ununsed files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ mediaplayer_install_location }}/mediaplayer/RadioList.json.sample"
    - "{{ mediaplayer_install_location }}/mediaplayer/run.sh"
    - "{{ mediaplayer_install_location }}/mediaplayer/scripts"
  changed_when: false

- name: Install app.properties
  template:
    src: app.properties
    dest: "{{ mediaplayer_install_location }}/mediaplayer/app.properties"
    owner: mediaplayer
    group: audio
    mode: 0640

- name: Generate RadioList.json
  include_tasks: 'radios.yml'

- name: Install mediaplayer.service
  template:
    src: systemd/system/mediaplayer.service
    dest: "/lib/systemd/system/{{ mediaplayer_systemd_name }}.service"
    owner: root
    group: root
    mode: 0640
  notify:
    - Enable and start service mediaplayer
    - Systemctl daemon reload
