---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  # only support LTS
  - name: ubuntu-bionic
    image: ubuntu:bionic
  - name: ubuntu-focal
    image: ubuntu:focal
provisioner:
  name: ansible
  # lint:
  #   name: ansible-lint
verifier:
  name: testinfra
#   lint:
#     name: flake8
